"""
pdf_exporter.py — Beautiful calendar-style PDF export
-----------------------------------------------------
Generates two polished PDFs:
 1. Master Exam Schedule — grouped by date/time, table layout
 2. Per-student Exam Schedule — personalized mini-calendar layout
"""

import os
import pandas as pd
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
)
from reportlab.lib.units import inch


# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------
def _timestamp_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Oblique", 8)
    footer_text = f"Generated by Exam Scheduler • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    canvas.drawCentredString(letter[0] / 2.0, 0.4 * inch, footer_text)
    canvas.restoreState()


def _format_date(day_str):
    try:
        return datetime.strptime(str(day_str), "%Y-%m-%d").strftime("%A, %b %d, %Y")
    except Exception:
        return str(day_str)


# -------------------------------------------------------------------
# MASTER SCHEDULE
# -------------------------------------------------------------------
def export_master_pdf(schedule_df, timeslots, outpath):
    """
    Export a clean, calendar-style master schedule grouped by day/time.
    """
    # Merge with time info
    df = schedule_df.merge(timeslots, on="timeslot_id", how="left")
    df["day_dt"] = pd.to_datetime(df["day"], errors="coerce")
    df = df.sort_values(["day_dt", "start_time", "course_name"])

    # Create PDF
    doc = SimpleDocTemplate(outpath, pagesize=landscape(letter),
                            rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    content = []

    title = Paragraph("<b><font size=18>📅 Master Exam Schedule</font></b>", styles["Title"])
    content.append(title)
    content.append(Spacer(1, 0.25 * inch))

    # Group by date
    for day, group in df.groupby("day"):
        if pd.isna(day):
            continue

        formatted_day = _format_date(day)
        content.append(Paragraph(f"<b><font size=13>{formatted_day}</font></b>", styles["Heading3"]))
        content.append(Spacer(1, 0.1 * inch))

        data = [["Course ID", "Course Name", "Start", "End", "Room"]]
        for _, row in group.iterrows():
            data.append([
                str(row["course_id"]),
                str(row["course_name"]),
                str(row.get("start_time", "--:--")),
                str(row.get("end_time", "--:--")),
                str(row.get("room_label", "TBD")),
            ])

        table = Table(data, colWidths=[1.2 * inch, 2.8 * inch, 1 * inch, 1 * inch, 2.2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e0ebff")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 11),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ]))
        content.append(table)
        content.append(Spacer(1, 0.3 * inch))

    doc.build(content, onFirstPage=_timestamp_footer, onLaterPages=_timestamp_footer)


# -------------------------------------------------------------------
# STUDENT-SPECIFIC CALENDAR PDFs
# -------------------------------------------------------------------
def export_student_pdfs(enrollments, schedule_df, timeslots, outdir, students_df=None):
    """
    Create personalized calendar-style PDFs for each student.
    """
    os.makedirs(outdir, exist_ok=True)
    df = schedule_df.merge(timeslots, on="timeslot_id", how="left")
    df["day_dt"] = pd.to_datetime(df["day"], errors="coerce")
    df = df.sort_values(["day_dt", "start_time", "course_name"])

    # Lookup
    student_info = {}
    if students_df is not None:
        for _, s in students_df.iterrows():
            sid = str(s["student_id"])
            student_info[sid] = {
                "name": f"{s.get('first_name', '')} {s.get('last_name', '')}".strip(),
                "email": s.get("email", "N/A")
            }

    grouped = enrollments.groupby("student_id")["course_id"].apply(list)

    for sid, course_list in grouped.items():
        sched = df[df["course_id"].isin(course_list)].copy()
        sched = sched.sort_values(["day_dt", "start_time", "course_name"])

        info = student_info.get(str(sid), {"name": f"Student {sid}", "email": "N/A"})
        name, email = info["name"], info["email"]

        # Create PDF
        safe_email = email.replace("@", "_at_").replace(".", "_")
        filename = f"{name.replace(' ', '_')}_{sid}_{safe_email}.pdf"
        path = os.path.join(outdir, filename)

        doc = SimpleDocTemplate(path, pagesize=letter,
                                rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()
        content = []

        header = Paragraph(
            f"<b><font size=16>🎓 {name}'s Exam Schedule</font></b><br/><font size=10>{email}</font>",
            styles["Title"]
        )
        content.append(header)
        content.append(Spacer(1, 0.3 * inch))

        if sched.empty:
            content.append(Paragraph("No exams scheduled.", styles["Normal"]))
            doc.build(content, onFirstPage=_timestamp_footer)
            continue

        for day, group in sched.groupby("day"):
            if pd.isna(day):
                continue
            formatted_day = _format_date(day)
            content.append(Paragraph(f"<b><font size=13>{formatted_day}</font></b>", styles["Heading3"]))
            content.append(Spacer(1, 0.1 * inch))

            data = [["Course ID", "Course Name", "Start", "End", "Room"]]
            for _, row in group.iterrows():
                data.append([
                    str(row["course_id"]),
                    str(row["course_name"]),
                    str(row.get("start_time", "--:--")),
                    str(row.get("end_time", "--:--")),
                    str(row.get("room_label", "TBD")),
                ])

            table = Table(data, colWidths=[1.2 * inch, 2.8 * inch, 1 * inch, 1 * inch, 2.2 * inch])
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#fff4e6")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 11),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ]))
            content.append(table)
            content.append(Spacer(1, 0.3 * inch))

        doc.build(content, onFirstPage=_timestamp_footer, onLaterPages=_timestamp_footer)
